/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  styledSystemSidebar: [
    { type: 'autogenerated', dirName: './docs/styled-system' },
  ],
};

module.exports = sidebars;
